apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: krg5w64pn-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7d8a5200cc.79x4.p3.openshiftapps.com/rhtap/rhtap-qe:4e57317e5137220a8d1d4f94cbbd47bd9b5ead77@sha256:8b8af394fb3271864a3794da5651d430d29cfd02ed5f8ebad3d7cec19fd828ac
          name: container-image
